### ISSUE TITLE
Correct "See also" in http://0x80.pl/articles/base64-simd-neon.html#see-also-update

### ISSUE THREAD

**Issue by mayeut** [WojciechMula/base64simd#4]
Hi,

First off thanks for your work, I'm always learning some new tricks reading your articles.

Just to clarify one thing in the see also of Neon base64 article: You mention Alfred Klomp developed the algorithm for libbase64 ARM64 decoding but what you're referring to is in fact one of my commits:
aklomp/base64@ac5c74a8de9f085f726ddb08ff11c781c43ee0ca
I'd very much appreciate a correction of the author there.

Thanks,
Matthieu Darbois

**Comment by WojciechMula** [comment]
Hi Matthieu, nice to hear it. BTW I was planning to contribute to Alfred's library, but you were faster. :)

I've just put your name in the article. Sorry for that, I didn't check file's history.

**Comment by mayeut** [comment]
Hi Wojciech, thanks for the correction. Very much appreciated.
